Added patches repo to installer script

diff --git a/scripts/buildbusybox b/scripts/buildbusybox
--- a/scripts/buildbusybox
+++ b/scripts/buildbusybox
@@ -20,13 +20,19 @@ fi
 
 if [ ! -d "$POSBUILDROOT/etc/targets/$TARGET" ]; then
         echo "No such target: $TARGET" >&2
-        exit
+        exit 1
 fi
 
 if [ ! -d "$BDIR_PRG" ]; then
 	echo "Creating build directory for $PRG: " $BDIR_PRG
 	mkdir "$BDIR_PRG"
 fi
+
+echo "Initializing config..."
+cp "$POSNKBUILDROOT/patch/posnk_busybox_config" "$BDIR_PRG/.config" || {
+	echo "Could not initialize busybox config!"
+	exit 1
+}
 
 cd "$SDIR_PRG"
 
@@ -35,17 +41,17 @@ echo "Building $PRG..."
 	make ARCH=$ARCH CROSS_COMPILE=$TARGET- O="$BDIR_PRG/" DESTDIR="$POSBUILDROOT/sysroot/$TARGET" $3
 } || {
 	echo "Failed to build $PRG!" >&2
-	exit
+	exit 1
 }
 
-#echo "Installing $PRG..."
-#{
+echo "Installing $PRG..."
+{
 #	make ARCH=$ARCH CROSS_COMPILE=$TARGET- O="$BDIR_PRG/" DESTDIR="$POSBUILDROOT/sysroot/$TARGET" install
-#	
-#} || {
-#	echo "Failed to install $PRG!" >&2
-#	exit
-#}
+	install "$BDIR_PKG/busybox" "$POSBUILDROOT/sysroot/$TARGET/sbin/busybox"	
+} || {
+	echo "Failed to install $PRG!" >&2
+	exit
+}
 
 echo "Done"
 
diff --git a/scripts/installenv b/scripts/installenv
--- a/scripts/installenv
+++ b/scripts/installenv
@@ -4,6 +4,7 @@
 
 INSTALLDIR=$1
 BUILDENVGIT="https://github.com/posnk/buildenv.git"
+PATCHESGIT="https://github.com/posnk/patches.git"
 
 if [ -z "$INSTALLDIR" ]; then
 	echo "Usage: installenv <install dir>" >&2
@@ -49,10 +50,20 @@ echo "Cloning build environment from git..."
 	exit
 }
 
+echo "Cloning patch collection from git..."
+{
+	cd src &&
+	git clone "$PATCHESGIT" &&
+	cd ..
+} || {
+	echo "Could not clone patches!" >&2
+	exit
+
 echo "Installing build environment binaries and configuration..."
 {
 	ln -s src/buildenv/scripts bin &&
-	ln -s src/buildenv/config etc
+	ln -s src/buildenv/config etc &&
+	ln -s src/patches patch &&
 } || {
 	echo "Could not install build environment!"
 	exit
