Started work on a package manager

diff --git a/scripts/pkg_build b/scripts/pkg_build
--- a/scripts/pkg_build
+++ b/scripts/pkg_build
@@ -7,14 +7,14 @@
 PKGMGR_TCPREFIX="$POSBUILDROOT/toolchains"
 PKGMGR_TARGET="$PKGENV_TARGET"
 PATH="$TCPREFIX/bin:$PATH"
-PKGMGR_CFGPKG="$PKGMGR_PKGDIR/targets/$TARGET/configure_opts"
-BDIR_PKG="build/$PKG-$TARGET"
-SDIR_PKG="$POSBUILDROOT/src3m/$PKG"
-PKGMGR_TRGROOT="$POSBUILDROOT/sysroot/$TARGET"
-PKGMGR_INTOKEN="$TRGROOT/var/pkgs/$PKGINFO_NAME""_inst"
-PKGMGR_CFGTOKEN="$TRGROOT/var/pkgs
+PKGMGR_CFGPKG="$PKGMGR_PKGDIR/targets/$PKGMGR_TARGET/configure_opts"
+BDIR_PKG="build/$PKGINFO_NAME-$PKGMGR_TARGET"
+SDIR_PKG="$POSBUILDROOT/src3m/$PKGINFO_NAME"
+PKGMGR_TRGROOT="$POSBUILDROOT/sysroot/$PKGMGR_TARGET"
+PKGMGR_INTOKEN="$PKGMGR_TRGROOT/var/pkgs/$PKGINFO_NAME""_inst"
+PKGMGR_CFGTOKEN="$PKGMGR_TRGROOT/var/pkgs/$PKGINFO_NAME""_cfg"
 
-if [ ( -f "$PKGMGR_INTOKEN" ) -a ( "$PKGMGR_FORCEIN" != "yes" )]; then
+if [ ( -f "$PKGMGR_INTOKEN" )  -a ( "$PKGMGR_FORCEIN" != "yes" )]; then
 	echo "Package $1 already installed"
 	echo "Run PKGMGR_FORCEIN=yes $0 $1 to force installation"
 	exit 0
@@ -47,45 +47,80 @@ if [ "$PKG_BUILDTYPE" = "autotools" ]; then
 	
 	. $PKGMGR_CFGPKG
 	
-	echo "Downloading package $PKGINFO_NAME ..."
-	fetchpkg "$PKGINFO_FETCHOPTS" "$PKGINFO_FETCHURL" || {
-		echo "Could not fetch package!"
+	if [ ! -d "$BDIR_PKG" ]; then
+		echo "Creating build directory for $PKGMGR_PKG ..."
+		mkdir "$BDIR_PKG" || {
+			echo "Failed to create build directory!"
+			exit 255
+		}
+	fi
+
+	echo "Configuring package $PKGMGR_PKG ..."
+
+	cd "$BDIR_PKG"
+	{
+		$SDIR_PKG/configure --host=$PKGMGR_TARGET --prefix="$PKGINFO_PREFIX" \
+			$PKG_CFG 
+	} || {
+		echo "Failed to configure package $PKGMGR_PKG !"
 		exit 255
 	}
 
+	echo "Building package $PKGMGR_PKG ..."
+	{
+		make tooldir="$PKGINFO_PREFIX" DESTDIR="$PKGMGR_TRGROOT" 
+	} || {
+		echo "Failed to build package $PKGMGR_PKG !"
+	}
 
-elif [ "$PKG_FETCHTYPE" = "git" ]; then
+elif [ "$PKG_BUILDTYPE" = "cmd" ]; then
 
-	echo "Cloning package $PKGINFO_NAME ..."
-	# TODO: Implement git packages
+	echo "Building package $PKGINFO_NAME ..."
+	{
+		$PKGINFO_BUILDCMD 
+	} || {
+		echo "Failed to build package $PKGMGR_PKG !"
+		exit 255
+	}
+
+elif [ "$PKG_BUILDTYPE" = "pos" ]; then
+
+	echo "Building package $PKGMGR_PKG ..."
+
+	BDIR_PRG="$POSBUILDROOT/build/$PKGINFO_NAME-$PKGMGR_TARGET"
+	SDIR_PRG="$POSBUILDROOT/src/$PKGINFO_NAME"
+	TCPREFIX="$POSBUILDROOT/toolchains"
+
+	if [ ! -d "$BDIR_PRG" ]; then
+		echo "Creating build directory for $PKGMGR_PKG"
+		mkdir "$BDIR_PRG"
+	fi
+
+	cd "$SDIR_PRG"
+
+	echo "Building $PKGMGR_PRG ..."
+	
+	{
+		make TARGET=$PKGMGR_TARGET BUILDDIR="$BDIR_PRG/" DESTDIR="$PKGMGR_TRGROOT"
+	} || {
+		echo "Failed to build $PKGMGR_PKG!"
+		exit 
+	}
+	
+	echo "Installing $PKGMGR_PRG ..."
+	{
+		make TARGET=$PKGMGR_TARGET BUILDDIR="$BDIR_PRG/" DESTDIR="$PKGMGR_TRGROOT" install
+	} || {
+		echo "Failed to install $PKGMGR_PKG!"
+	}
 
 else
 
-	echo "Invalid package fetch type!"
+	echo "Invalid package build type!"
 	exit 255
 
 fi
 
-if [ "$PKG_DOPATCH" = "yes"]; then
-
-	echo "Patching upstream package..."
-
-	patchpkg "$PKGINFO_NAME" || {
-		echo "Could not patch package!"
-		exit 255
-	}
-
-else
-
-	editpkg "$PKGINFO_NAME"	|| {
-		echo "Could not instantiate local clone..."
-		exit 255
-	}
-
-fi
-
-touch $PKGMGR_DLTOKEN
-
-echo Package downloaded!
+echo Package installed.
 
 exit 0
diff --git a/scripts/pkg_get b/scripts/pkg_get
--- a/scripts/pkg_get
+++ b/scripts/pkg_get
@@ -6,7 +6,7 @@
 
 PKGMGR_DLTOKEN="$POSBUILDROOT/var/pkgs/$PKGINFO_NAME""_dl"
 
-if [ "$PKGMGR_FETCHTYPE" = "meta" ]; then
+if [ "$PKGINFO_FETCHTYPE" = "meta" ]; then
 
 	exit 0
 
@@ -35,23 +35,34 @@ fi
 
 if [ "$PKGINFO_FETCHTYPE" = "dist" ]; then
 
-	if [ "$PKGMGR_VERBOSE" = "yes" ]; then
-		echo "Doing dist fetch"
-		echo "Extraction options: $PKGINFO_FETCHOPTS"
-		echo "Download URL: $PKGINFO_FETCHURL"
-	fi	
+	if [ -d "$POSBUILDROOT/src3p/$PKGINFO_NAME" ]; then 
 
-	echo "Downloading package $PKGINFO_NAME ..."
-	fetchpkg "$PKGINFO_FETCHOPTS" "$PKGINFO_FETCHURL" || {
-		echo "Could not fetch package!"
-		exit 255
-	}
+		echo "Upstream source already downloaded"
+
+	else
+
+		if [ "$PKGMGR_VERBOSE" = "yes" ]; then
+			echo "Doing dist fetch"
+			echo "Extraction options: $PKGINFO_FETCHOPTS"
+			echo "Download URL: $PKGINFO_FETCHURL"
+		fi	
+
+		echo "Downloading package $PKGINFO_NAME ..."
+		fetchpkg "$PKGINFO_FETCHOPTS" "$PKGINFO_FETCHURL" || {
+			echo "Could not fetch package!"
+			exit 255
+		}
+
+	fi
 
 
 elif [ "$PKGINFO_FETCHTYPE" = "git" ]; then
 
 	echo "Cloning package $PKGINFO_PKG ..."
-	# TODO: Implement git packages
+
+	cd "$POSBUILDROOT/src"
+
+	git clone "$PKGINFO_GITURL"
 
 else
 
@@ -59,8 +70,7 @@ else
 	exit 255
 
 fi
-
-if [ "$PKG_PATCHTYPE" = "old"]; then
+if [ "$PKGINFO_PATCHTYPE" = "old" ]; then
 
 	echo "Patching upstream package..."
 
@@ -77,7 +87,7 @@ if [ "$PKG_PATCHTYPE" = "old"]; then
 		exit 255
 	}
 
-elif [ "$PKG_PATCHTYPE" = "pkg" ]; then
+elif [ "$PKGINFO_PATCHTYPE" = "pkg" ]; then
 
 	echo "Patching upstream package..."
 
@@ -86,7 +96,7 @@ elif [ "$PKG_PATCHTYPE" = "pkg" ]; then
 		exit 255
 	fi
 
-	if [ ! -d "$PKGMGR_PKGDIR/posnk.patch" ]; then
+	if [ ! -f "$PKGMGR_PKGDIR/posnk.patch" ]; then
 		echo "Missing patchfile for package $PKGMGR_PKG !"
 		exit 255
 	fi
@@ -104,7 +114,7 @@ elif [ "$PKG_PATCHTYPE" = "pkg" ]; then
 	cp -r "../src3p/$PKGINFO_NAME" "./$PKGINFO_NAME"
 	patch -p0 < "$PKGMGR_PKGDIR/posnk.patch"	
 
-elif [ "$PKG_PATCHTYPE" = "upstream" ]; then
+elif [ "$PKGINFO_PATCHTYPE" = "upstream" ]; then
 
 	editpkg "$PKGINFO_NAME"	|| {
 		echo "Could not instantiate local clone..."
